//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ibags.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AccountId { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Country { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public int rowId { get; set; }
    }
}
