//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ibags.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IbagsDbContext : DbContext
    {
        public IbagsDbContext()
            : base("name=IbagsDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<News> NewsSet { get; set; }
        public DbSet<Order> OrderSet { get; set; }
        public DbSet<Account> AccountSet { get; set; }
        public DbSet<Message> MessageSet { get; set; }
    }
}
