//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ibags.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Content { get; set; }
        public string MobileNo { get; set; }
        public int MessageType { get; set; }
        public int RetryCount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ResultCode { get; set; }
    }
}
